### ISSUE TITLE
spacing and presentation enhancements of gridfield

### ISSUE THREAD

**Issue by sunnysideup** [UndefinedOffset/SortableGridField#122]
## Affected Version

SS4

## Description

![image](https://user-images.githubusercontent.com/167154/43051829-4ccd46e0-8e73-11e8-9b25-e5e80c80f708.png)

There seems to be too much spacing here in places where things should be tight (e.g. too much spacing between headers and rows) and perhaps also vice versa.

This is of course part of the core GridField, but it may be an idea to at least let the sortable gridfield do it a little better?

**Comment by sunnysideup** [comment]
here is what can be achieved in a few minutes with CSS (and my limited abilities):

![image](https://user-images.githubusercontent.com/167154/43051904-053a1f64-8e74-11e8-9408-e6c769a01fa0.png)

**Comment by sunnysideup** [comment]
This is the CSS I added:

```css

table.grid-field__table  .sortablerowsheading {
  padding-top: 0!important; padding-bottom: 0!important; background-color: #ddd;
  border-bottom: 1px solid #aaa;
}

table.grid-field__table th.main {
  border-bottom: 1px solid #aaa;
  background-color: #ccc;
}
```
